### ISSUE TITLE
Corner bewerten

### ISSUE THREAD

**Issue by robme91** [robme91/ebp-berlincorner#5]
Nach aktuellem stand, habe ich keine Ahnung wo ich eine Bewertung einbauen soll. Eigentlich müsste dann beim Click auf nen corner iwas aufgehen, wo man raten kann. Das Popub ding, erlaubt nur inline html, was die ganze sache unübersichtlich machen würde und kp ob das überhaupt funzt dann. 
Eventuell drauf scheißen???

**Comment by devfoo-one** [comment]
Haha 😂 Jaaa, ich erinnere mich an die Schmerzen. Lass weg... is nicht relevant.

**Comment by robme91** [comment]
okay wir lassens
